ams/urls.py
from django.conf.urls import url
from . import views

app_name = 'ams'

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^login_user/$', views.login_user, name='login_user'),
    url(r'^logout_user/$', views.logout_user, name='logout_user'),
    url(r'^subordinates/$', views.subordinates, name='subordinates'),
    url(r'^subordinates/(?P<employee_id>[0-9]+)/approval/$', views.approval, name='approval'),
    url(r'^subordinates/(?P<ownership_id>[0-9]+)/approved/$', views.approved, name='approved'),
    url(r'^employees/$', views.employees, name='employees'),
    url(r'^employees/(?P<employee_id>[0-9]+)/$', views.employee_detail, name='employee_detail'),
    url(r'^employee_report/$', views.employee_report, name='employee_report'),
    url(r'^asset_report/$', views.asset_report, name='asset_report'),
    url(r'^request_asset/$', views.request_asset, name='request_asset'),
]

web/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^ams/', include('ams.urls')),
    url(r'^', include('ams.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

ams/models.py
from django.contrib.auth.models import Permission, User
from django.db import models


class Department(models.Model):
    department_name = models.CharField(max_length=250)

    def __str__(self):
        return self.department_name


class Employee(models.Model):
    user = models.OneToOneField(User)
    employee_name = models.CharField(max_length=250)
    department = models.ForeignKey(Department, default=1, on_delete=models.CASCADE)
    manager = models.ForeignKey('self', null=True, related_name='employee')

    def __str__(self):
        return self.employee_name


class Asset(models.Model):
    asset_name = models.CharField(max_length=250)

    def __str__(self):
        return self.asset_name


class Ownership(models.Model):
    BOOKED = 'Booked asset'
    APPROVED = 'Approved'

    STATUS_TYPE = (
        (BOOKED, 'Booked asset'),
        (APPROVED, 'Approved')
    )

    owner = models.ForeignKey(Employee, on_delete=models.CASCADE)
    asset = models.ForeignKey(Asset, on_delete=models.CASCADE)
    status = models.CharField(max_length=20, choices=STATUS_TYPE)

    def __str__(self):
        return str(self.owner) + ' - ' + str(self.asset) + ' - ' + self.status

ams/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import Ownership


class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ['username', 'email', 'password']


class AssetForm(forms.ModelForm):

    class Meta:
        model = Ownership
        fields = ['asset']

ams/views.py
from django.contrib.auth import authenticate, login, logout
from django.shortcuts import render, get_object_or_404

from .forms import UserForm, AssetForm
from .models import *


def index(request):
    if not request.user.is_authenticated():
        return render(request, 'ams/login.html')
    else:
        employee = Employee.objects.filter(user=request.user)
        assets = Ownership.objects.filter(owner=employee)
        return render(request, 'ams/index.html', {'assets': assets})


def logout_user(request):
    logout(request)
    form = UserForm(request.POST or None)
    context = {
        "form": form,
    }
    return render(request, 'ams/login.html', context)


def login_user(request):
    if request.method == "POST":
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(username=username, password=password)
        if user is not None:
            if user.is_active:
                login(request, user)
                employee = Employee.objects.filter(user=request.user)
                assets = Ownership.objects.filter(owner=employee)
                return render(request, 'ams/index.html', {'assets': assets})
            else:
                return render(request, 'ams/login.html', {'error_message': 'Your account has been disabled'})
        else:
            return render(request, 'ams/login.html', {'error_message': 'Invalid login'})
    return render(request, 'ams/login.html')


def subordinates(request):
    if not request.user.is_authenticated():
        return render(request, 'ams/login.html')
    else:
        employee = Employee.objects.filter(user=request.user)
        all_subordinates = Employee.objects.filter(manager=employee)
        for sub in all_subordinates:
            booked = Ownership.objects.filter(owner=sub, status=Ownership.BOOKED)
            setattr(sub, 'booked', booked.count())
        return render(request, 'ams/subordinates.html', {'all_subordinates': all_subordinates})


def approval(request, employee_id):
    if not request.user.is_authenticated():
        return render(request, 'ams/login.html')
    else:
        employee = Employee.objects.filter(pk=employee_id)
        assets = Ownership.objects.filter(owner=employee)
        return render(request, 'ams/approval.html', {'assets': assets})


def approved(request, ownership_id):
    asset = get_object_or_404(Ownership, pk=ownership_id)
    all_subordinates = Employee
    try:
        asset.status = Ownership.APPROVED
        asset.save()
        employee = Employee.objects.filter(user=request.user)
        all_subordinates = Employee.objects.filter(manager=employee)
        for sub in all_subordinates:
            booked = Ownership.objects.filter(owner=sub, status=Ownership.BOOKED)
            setattr(sub, 'booked', booked.count())
    except (KeyError, Asset.DoesNotExist):
        return render(request, 'ams/subordinates.html', {'all_subordinates': all_subordinates})
    else:
        return render(request, 'ams/subordinates.html', {'all_subordinates': all_subordinates})


def employees(request):
    if not request.user.is_authenticated():
        return render(request, 'ams/login.html')
    else:
        all_employees = Employee.objects.all()
        return render(request, 'ams/employees.html', {'all_employees': all_employees})


def get_subordinates(emp):
    if Employee.objects.filter(manager=emp).count() > 0:
        emp_name = [emp.employee_name]
        all_subs = Employee.objects.filter(manager=emp)
        for sub in all_subs:
            emp_name.append(get_subordinates(sub))
        return emp_name
    else:
        return emp.employee_name


def deep_len(lst):
    return sum(deep_len(el) if isinstance(el, list) else 1 for el in lst)


def employee_detail(request, employee_id):
    if not request.user.is_authenticated():
        return render(request, 'ams/login.html')
    else:
        employee = Employee.objects.get(pk=employee_id)
        all_subordinates = get_subordinates(employee)
        if isinstance(all_subordinates, str):
                all_subordinates = [all_subordinates]
        return render(request, 'ams/employee_detail.html', {'all_subordinates': all_subordinates})


def employee_report(request):
    if not request.user.is_authenticated():
        return render(request, 'ams/login.html')
    else:
        all_employees = Employee.objects.all()
        for employee in all_employees:
            all_subordinates = get_subordinates(employee)
            if isinstance(all_subordinates, str):
                all_subordinates = [all_subordinates]
            setattr(employee, 'subordinates', deep_len(all_subordinates)-1)
        return render(request, 'ams/employee_report.html', {'all_employees': all_employees})


def asset_report(request):
    if not request.user.is_authenticated():
        return render(request, 'ams/login.html')
    else:
        all_departments = Department.objects.all()
        for dept in all_departments:
            employees_dept = Employee.objects.filter(department=dept)
            setattr(dept, 'employees', employees_dept.count())
            asset_count = 0
            for emp in employees_dept:
                asset_count += Ownership.objects.filter(owner=emp, status="Approved").count()
            setattr(dept, 'assets', asset_count)
        return render(request, 'ams/asset_report.html', {'all_departments': all_departments})


def request_asset(request):
    if not request.user.is_authenticated():
        return render(request, 'ams/login.html')
    else:
        form = AssetForm(request.POST or None)
        if form.is_valid():
            employee = Employee.objects.get(user=request.user)
            asset = form.save(commit=False)
            asset.owner = employee
            if employee.manager is not None:
                asset.status = Ownership.BOOKED
            else:
                asset.status = Ownership.APPROVED
            asset.save()
            assets = Ownership.objects.filter(owner=employee)
            return render(request, 'ams/index.html', {'assets': assets})
        context = {
            "form": form,
        }
        return render(request, 'ams/request_asset.html', context)

ams/templates/ams/approval.html
{% extends 'ams/base.html' %}
{% block subordinates_active %}active{% endblock %}

{% block body %}
<div class="approval-container container-fluid">

    <h2>{{ assets.0.owner }}'s asset</h2>
    {% if assets %}
        <table class="table table-hover"><br/>
            <thead>
                <tr>
                    <th scope="col">No.</th>
                    <th scope="col">Asset</th>
                    <th scope="col">Status</th>
                    <th scope="col">Action</th>
                </tr>
            </thead>
            {% for asset in assets %}
                <tbody>
                    <tr>
                        <td>{{ forloop.counter }}</td>
                        <td>{{ asset.asset }}</td>
                        <td>{{ asset.status }}</td>
                        <td>
                            <a href="{% url 'ams:approved' asset.id %}" class="btn-approval">
                                <span class="approval {% if asset.status == 'Approved' %}approved{% endif %}">Approve</span>
                            </a>
                        </td>
                    </tr>
                </tbody>
            {% endfor %}
        </table>
    {% else %}
        <h1>{{ asset.owner }} doesn't have any assets</h1>
    {% endif %}

</div>
{% endblock %}

ams/templates/ams/asset_report.html
{% extends 'ams/base.html' %}
{% block asset_report_active %}active{% endblock %}

{% block body %}
<div class="asset-report-container container-fluid">

    <!-- Asset Report -->
    {% if all_departments %}
        <table class="table table-hover">
            <thead>
                <tr>
                    <th scope="col">No.</th>
                    <th scope="col">Department</th>
                    <th scope="col">Employees</th>
                    <th scope="col">Assets</th>
                </tr>
            </thead>
            {% for dept in all_departments %}
                <tbody>
                    <tr>
                        <td>{{ forloop.counter }}</td>
                        <td>{{ dept.department_name }}</td>
                        <td>{{ dept.employees }}</td>
                        <td>{{ dept.assets }}</td>
                    </tr>
                </tbody>
            {% endfor %}
        </table>
    {% else %}
        <h1>There is no departments</h1>
    {% endif %}

</div>
{% endblock %}

ams/templates/ams/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Asset Management System{% endblock %}</title>
    {% load staticfiles %}
    <link href="{% static 'favicon.png' %}" rel="shortcut icon" type="image/png"/>
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Lobster|Open+Sans" rel="stylesheet" type="text/css">
    <link href="{% static 'ams/style.css' %}" rel="stylesheet" type="text/css"/>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
</head>
<body>
<nav class="navbar navbar-inverse">
    <div class="container-fluid">

        <!-- Header -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{% url 'ams:index' %}">Asset Management System</a>
        </div>

        <!-- Items -->
        <div class="collapse navbar-collapse" id="topNavBar">
            <ul class="nav navbar-nav">
                <li class="{% block assets_active %}{% endblock %}">
                    <a href="{% url 'ams:index' %}">
                        <span class="glyphicon glyphicon-briefcase" aria-hidden="true"></span>&nbsp; Your Asset
                    </a>
                </li>
                <li class="{% block subordinates_active %}{% endblock %}">
                    <a href="{% url 'ams:subordinates' %}">
                        <span class="glyphicon glyphicon-arrow-down" aria-hidden="true"></span>&nbsp; Your Subordinates
                    </a>
                </li>
                <li class="{% block employees_active %}{% endblock %}">
                    <a href="{% url 'ams:employees' %}">
                        <span class="glyphicon glyphicon-user" aria-hidden="true"></span>&nbsp; All Employees
                    </a>
                </li>
                <li class="{% block employee_report_active %}{% endblock %}">
                    <a href="{% url 'ams:employee_report' %}">
                        <span class="glyphicon glyphicon-list-alt" aria-hidden="true"></span>&nbsp; Employee Report
                    </a>
                </li>
                <li class="{% block asset_report_active %}{% endblock %}">
                    <a href="{% url 'ams:asset_report' %}">
                        <span class="glyphicon glyphicon-list" aria-hidden="true"></span>&nbsp; Asset Report
                    </a>
                </li>
            </ul>
            <ul class="nav navbar-nav navbar-right">
                <li class="{% block request_asset_active %}{% endblock %}">
                    <a href="{% url 'ams:request_asset' %}">
                        <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>&nbsp; Request Asset
                    </a>
                </li>
                <li>
                    <a href="{% url 'ams:logout_user' %}">
                        <span class="glyphicon glyphicon-off" aria-hidden="true"></span>&nbsp; Logout
                    </a>
                </li>
            </ul>
        </div>

    </div>
</nav>
{% block body %}
{% endblock %}
</body>
</html>

ams/templates/ams/base_visitor.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Asset Management System{% endblock %}</title>
    {% load staticfiles %}
    <link href="{% static 'favicon.png' %}" rel="shortcut icon" type="image/png"/>
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Lobster|Open+Sans" rel="stylesheet" type="text/css">
    <link href="{% static 'ams/style.css' %}" rel="stylesheet" type="text/css"/>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
</head>
<body>
<nav class="navbar navbar-inverse">
    <div class="container-fluid">

        <!-- Header -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{% url 'ams:index' %}">Asset Management System</a>
        </div>

        <!-- Items -->
        <div class="collapse navbar-collapse" id="topNavBar">
            <ul class="nav navbar-nav">
                <li class="{% block login_active %}{% endblock %}"><a href="{% url 'ams:login_user' %}">Log In</a></li>
            </ul>
        </div>

    </div>
</nav>
{% block body %}
{% endblock %}
</body>
</html>

ams/templates/ams/employee_detail.html
{% extends 'ams/base.html' %}
{% block employees_active %}active{% endblock %}

{% block body %}
<div class="employee-detail-container container-fluid">
    {{ all_subordinates }}
</div>
{% endblock %}

ams/templates/ams/employee_report.html
{% extends 'ams/base.html' %}
{% block employee_report_active %}active{% endblock %}

{% block body %}
<div class="employee-report-container container-fluid">

    <!-- Employee Report -->
    {% if all_employees %}
        <table class="table table-hover">
            <thead>
                <tr>
                    <th scope="col">No.</th>
                    <th scope="col">Name</th>
                    <th scope="col">Department</th>
                    <th scope="col">Subordinates</th>
                </tr>
            </thead>
            {% for employee in all_employees %}
                <tbody>
                    <tr>
                        <td>{{ forloop.counter }}</td>
                        <td>{{ employee.employee_name }}</td>
                        <td>{{ employee.department }}</td>
                        <td>{{ employee.subordinates }}</td>
                    </tr>
                </tbody>
            {% endfor %}
        </table>
    {% else %}
        <h1>There is no employees</h1>
    {% endif %}

</div>
{% endblock %}

ams/templates/ams/employees.html
{% extends 'ams/base.html' %}
{% block employees_active %}active{% endblock %}

{% block body %}
<div class="employees-container container-fluid">

    <!-- Employees -->
    {% if all_employees %}
        <table class="table table-hover">
            <thead>
                <tr>
                    <th scope="col">No.</th>
                    <th scope="col">Name</th>
                    <th scope="col">Department</th>
                    <th scope="col">Manager</th>
                </tr>
            </thead>
            {% for employee in all_employees %}
                <tbody>
                    <tr>
                        <td>{{ forloop.counter }}</td>
                        <td>
                            <a href="{% url 'ams:employee_detail' employee.id %}">{{ employee.employee_name }}</a>
                        </td>
                        <td>{{ employee.department }}</td>
                        {% if employee.manager is None %}
                            <td>-</td>
                        {% else %}
                            <td>{{ employee.manager }}</td>
                        {% endif %}
                    </tr>
                </tbody>
            {% endfor %}
        </table>
    {% else %}
        <h1>There is no employees</h1>
    {% endif %}

</div>
{% endblock %}

ams/templates/ams/form_template.html
{% for field in form %}
    <div class="form-group">
        <label class="control-label col-sm-2" for="asset">{{ field.label_tag }}</label>
        <div class="col-sm-10">{{ field }}</div>
    </div>
{% endfor %}

ams/templates/ams/index.html
{% extends 'ams/base.html' %}
{% block assets_active %}active{% endblock %}

{% block body %}
<div class="assets-container container-fluid">

    <!-- Asset -->
    {% if assets %}
        <table class="table table-hover">
            <thead>
                <tr>
                    <th scope="col">No.</th>
                    <th scope="col">Asset</th>
                    <th scope="col">Status</th>
                </tr>
            </thead>
            {% for asset in assets %}
                <tbody>
                    <tr>
                        <td>{{ forloop.counter }}</td>
                        <td>{{ asset.asset }}</td>
                        <td>{{ asset.status }}</td>
                    </tr>
                </tbody>
            {% endfor %}
        </table>
    {% else %}
        <h1>You don't have any assets</h1>
    {% endif %}

</div>
{% endblock %}

ams/templates/ams/login.html
{% extends 'ams/base_visitor.html' %}
{% block title %}Log In{% endblock %}
{% block login_active %}active{% endblock %}

{% block body %}
<div class="container-fluid">

    <!-- Login -->
    <div class="row">
        <div class="col-sm-12 col-md-6">
            <div class="panel panel-default">
                <div class="panel-body">
                    <h3>Log In</h3>
                    {% if error_message %}
                        <p><strong>{{ error_message }}</strong></p>
                    {% endif %}
                    <form class="form-horizontal" role="form" action="{% url 'ams:login_user' %}" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        <div class="form-group">
                            <label class="control-label col-sm-2" for="id_username">
                                Username:
                            </label>
                            <div class="col-sm-10">
                                <input id="id_username" maxlength="30" name="username" type="text">
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="control-label col-sm-2" for="id_password">
                                Password:
                            </label>
                            <div class="col-sm-10">
                                <input id="id_password" maxlength="30" name="password" type="password">
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <button type="submit" class="btn btn-success">Submit</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>

</div>

{% endblock %}

ams/templates/ams/request_asset.html
{% extends 'ams/base.html' %}
{% block title %}Request Asset{% endblock %}
{% block request_asset_active %}active{% endblock %}

{% block body %}
<div class="container-fluid">

    <!-- Request Asset -->
    <div class="row">
        <div class="col-sm-12 col-sm-4">
            <div class="panel panel-default">
                <div class="panel-body">
                    <h3>Request asset</h3><br/>
                    {% if error_message %}
                        <p><strong>{{ error_message }}</strong></p>
                    {% endif %}
                    <form class="form-horizontal" role="form" action="" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {% include 'ams/form_template.html' %}
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <button type="submit" class="btn btn-success">Submit</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>

</div>
{% endblock %}

ams/templates/ams/subordinates.html
{% extends 'ams/base.html' %}
{% block subordinates_active %}active{% endblock %}

{% block body %}
<div class="subordinates-container container-fluid">

    <!-- Subordinates -->
    {% if all_subordinates %}
        <table class="table table-hover">
            <thead>
                <tr>
                    <th scope="col">No.</th>
                    <th scope="col">Name</th>
                    <th scope="col">Booked asset</th>
                </tr>
            </thead>
            {% for employee in all_subordinates %}
                <tbody>
                    <tr>
                        <td>{{ forloop.counter }}</td>
                        <td>{{ employee.employee_name }}</td>
                        {% if employee.booked %}
                            <td>{{ employee.booked }}&nbsp; (<a href="{% url 'ams:approval' employee.id %}">Approval</a>)</td>
                        {% else %}
                            <td>{{ employee.booked }}</td>
                        {% endif %}
                    </tr>
                </tbody>
            {% endfor %}
        </table>
    {% else %}
        <h1>You don't have any subordinates</h1>
    {% endif %}

</div>
{% endblock %}